spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: trouble
    url: jdbc:mysql://120.25.201.1/NewsApp?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /newsApp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

